name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Project
        # Ensure this command builds your project correctly
        run: |
          # Replace this command with the actual command needed for your build
          python build_script.py

      - name: Disable Jekyll
        # This ensures GitHub Pages doesn't interpret it as a Jekyll site
        run: echo "" > ./output_dir/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output_dir  # Ensure this is the correct build output directory
