name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Updated version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated version
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Project
        # Replace with your build command if necessary
        run: |
          # Example build command, modify as needed
          python build_script.py

      - name: Disable Jekyll
        run: echo "" > ./output_dir/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output_dir  # Specify your output directory
